/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _Group10: THREE.Mesh;
    _Group2: THREE.Mesh;
    _Group3: THREE.Mesh;
    _Group4: THREE.Mesh;
    _Group5: THREE.Mesh;
    _Group6: THREE.Mesh;
    _Group7: THREE.Mesh;
    _Group8: THREE.Mesh;
    _Group9: THREE.Mesh;
    Group10: THREE.Mesh;
    Group11: THREE.Mesh;
    Group12: THREE.Mesh;
    Group13: THREE.Mesh;
    Group14: THREE.Mesh;
    Group15: THREE.Mesh;
    Group16: THREE.Mesh;
    Group17: THREE.Mesh;
    Group18: THREE.Mesh;
    Group19: THREE.Mesh;
    Group2: THREE.Mesh;
    Group20: THREE.Mesh;
    Group21: THREE.Mesh;
    Group22: THREE.Mesh;
    Group23: THREE.Mesh;
    Group24: THREE.Mesh;
    Group25: THREE.Mesh;
    Group26: THREE.Mesh;
    Group28: THREE.Mesh;
    Group29: THREE.Mesh;
    Group3: THREE.Mesh;
    Group30: THREE.Mesh;
    Group31: THREE.Mesh;
    Group32: THREE.Mesh;
    Group33: THREE.Mesh;
    Group34: THREE.Mesh;
    Group35: THREE.Mesh;
    Group4: THREE.Mesh;
    Group5: THREE.Mesh;
    Group6: THREE.Mesh;
    Group61531: THREE.Mesh;
    Group7: THREE.Mesh;
    Group8: THREE.Mesh;
    ZBrush_defualt_group: THREE.Mesh;
  };
  materials: {
    lambert112SG: THREE.MeshPhysicalMaterial;
  };
};

export function ModelChair(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/silla.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="1OBJ"
        position={[0.27027541, 0.62835461, -1.52376175]}
        rotation={[3.11965071, -0.70957532, 3.13347309]}
        scale={[0.63306296, 0.63306296, 0.63306302]}
        userData={{ name: "1.OBJ" }}
      >
        <group name="g__Group10" userData={{ name: "g _Group10" }}>
          <mesh
            name="_Group10"
            castShadow
            receiveShadow
            geometry={nodes._Group10.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group10" }}
          />
        </group>
        <group name="g__Group2" userData={{ name: "g _Group2" }}>
          <mesh
            name="_Group2"
            castShadow
            receiveShadow
            geometry={nodes._Group2.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group2" }}
          />
        </group>
        <group name="g__Group3" userData={{ name: "g _Group3" }}>
          <mesh
            name="_Group3"
            castShadow
            receiveShadow
            geometry={nodes._Group3.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group3" }}
          />
        </group>
        <group name="g__Group4" userData={{ name: "g _Group4" }}>
          <mesh
            name="_Group4"
            castShadow
            receiveShadow
            geometry={nodes._Group4.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group4" }}
          />
        </group>
        <group name="g__Group5" userData={{ name: "g _Group5" }}>
          <mesh
            name="_Group5"
            castShadow
            receiveShadow
            geometry={nodes._Group5.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group5" }}
          />
        </group>
        <group name="g__Group6" userData={{ name: "g _Group6" }}>
          <mesh
            name="_Group6"
            castShadow
            receiveShadow
            geometry={nodes._Group6.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group6" }}
          />
        </group>
        <group name="g__Group7" userData={{ name: "g _Group7" }}>
          <mesh
            name="_Group7"
            castShadow
            receiveShadow
            geometry={nodes._Group7.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group7" }}
          />
        </group>
        <group name="g__Group8" userData={{ name: "g _Group8" }}>
          <mesh
            name="_Group8"
            castShadow
            receiveShadow
            geometry={nodes._Group8.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group8" }}
          />
        </group>
        <group name="g__Group9" userData={{ name: "g _Group9" }}>
          <mesh
            name="_Group9"
            castShadow
            receiveShadow
            geometry={nodes._Group9.geometry}
            material={materials.lambert112SG}
            userData={{ name: "_Group9" }}
          />
        </group>
        <group name="g_Group10" userData={{ name: "g Group10" }}>
          <mesh
            name="Group10"
            castShadow
            receiveShadow
            geometry={nodes.Group10.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group10" }}
          />
        </group>
        <group name="g_Group11" userData={{ name: "g Group11" }}>
          <mesh
            name="Group11"
            castShadow
            receiveShadow
            geometry={nodes.Group11.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group11" }}
          />
        </group>
        <group name="g_Group12" userData={{ name: "g Group12" }}>
          <mesh
            name="Group12"
            castShadow
            receiveShadow
            geometry={nodes.Group12.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group12" }}
          />
        </group>
        <group name="g_Group13" userData={{ name: "g Group13" }}>
          <mesh
            name="Group13"
            castShadow
            receiveShadow
            geometry={nodes.Group13.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group13" }}
          />
        </group>
        <group name="g_Group14" userData={{ name: "g Group14" }}>
          <mesh
            name="Group14"
            castShadow
            receiveShadow
            geometry={nodes.Group14.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group14" }}
          />
        </group>
        <group name="g_Group15" userData={{ name: "g Group15" }}>
          <mesh
            name="Group15"
            castShadow
            receiveShadow
            geometry={nodes.Group15.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group15" }}
          />
        </group>
        <group name="g_Group16" userData={{ name: "g Group16" }}>
          <mesh
            name="Group16"
            castShadow
            receiveShadow
            geometry={nodes.Group16.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group16" }}
          />
        </group>
        <group name="g_Group17" userData={{ name: "g Group17" }}>
          <mesh
            name="Group17"
            castShadow
            receiveShadow
            geometry={nodes.Group17.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group17" }}
          />
        </group>
        <group name="g_Group18" userData={{ name: "g Group18" }}>
          <mesh
            name="Group18"
            castShadow
            receiveShadow
            geometry={nodes.Group18.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group18" }}
          />
        </group>
        <group name="g_Group19" userData={{ name: "g Group19" }}>
          <mesh
            name="Group19"
            castShadow
            receiveShadow
            geometry={nodes.Group19.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group19" }}
          />
        </group>
        <group name="g_Group2" userData={{ name: "g Group2" }}>
          <mesh
            name="Group2"
            castShadow
            receiveShadow
            geometry={nodes.Group2.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group2" }}
          />
        </group>
        <group name="g_Group20" userData={{ name: "g Group20" }}>
          <mesh
            name="Group20"
            castShadow
            receiveShadow
            geometry={nodes.Group20.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group20" }}
          />
        </group>
        <group name="g_Group21" userData={{ name: "g Group21" }}>
          <mesh
            name="Group21"
            castShadow
            receiveShadow
            geometry={nodes.Group21.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group21" }}
          />
        </group>
        <group name="g_Group22" userData={{ name: "g Group22" }}>
          <mesh
            name="Group22"
            castShadow
            receiveShadow
            geometry={nodes.Group22.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group22" }}
          />
        </group>
        <group name="g_Group23" userData={{ name: "g Group23" }}>
          <mesh
            name="Group23"
            castShadow
            receiveShadow
            geometry={nodes.Group23.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group23" }}
          />
        </group>
        <group name="g_Group24" userData={{ name: "g Group24" }}>
          <mesh
            name="Group24"
            castShadow
            receiveShadow
            geometry={nodes.Group24.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group24" }}
          />
        </group>
        <group name="g_Group25" userData={{ name: "g Group25" }}>
          <mesh
            name="Group25"
            castShadow
            receiveShadow
            geometry={nodes.Group25.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group25" }}
          />
        </group>
        <group name="g_Group26" userData={{ name: "g Group26" }}>
          <mesh
            name="Group26"
            castShadow
            receiveShadow
            geometry={nodes.Group26.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group26" }}
          />
        </group>
        <group name="g_Group28" userData={{ name: "g Group28" }}>
          <mesh
            name="Group28"
            castShadow
            receiveShadow
            geometry={nodes.Group28.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group28" }}
          />
        </group>
        <group name="g_Group29" userData={{ name: "g Group29" }}>
          <mesh
            name="Group29"
            castShadow
            receiveShadow
            geometry={nodes.Group29.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group29" }}
          />
        </group>
        <group name="g_Group3" userData={{ name: "g Group3" }}>
          <mesh
            name="Group3"
            castShadow
            receiveShadow
            geometry={nodes.Group3.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group3" }}
          />
        </group>
        <group name="g_Group30" userData={{ name: "g Group30" }}>
          <mesh
            name="Group30"
            castShadow
            receiveShadow
            geometry={nodes.Group30.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group30" }}
          />
        </group>
        <group name="g_Group31" userData={{ name: "g Group31" }}>
          <mesh
            name="Group31"
            castShadow
            receiveShadow
            geometry={nodes.Group31.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group31" }}
          />
        </group>
        <group name="g_Group32" userData={{ name: "g Group32" }}>
          <mesh
            name="Group32"
            castShadow
            receiveShadow
            geometry={nodes.Group32.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group32" }}
          />
        </group>
        <group name="g_Group33" userData={{ name: "g Group33" }}>
          <mesh
            name="Group33"
            castShadow
            receiveShadow
            geometry={nodes.Group33.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group33" }}
          />
        </group>
        <group name="g_Group34" userData={{ name: "g Group34" }}>
          <mesh
            name="Group34"
            castShadow
            receiveShadow
            geometry={nodes.Group34.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group34" }}
          />
        </group>
        <group name="g_Group35" userData={{ name: "g Group35" }}>
          <mesh
            name="Group35"
            castShadow
            receiveShadow
            geometry={nodes.Group35.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group35" }}
          />
        </group>
        <group name="g_Group4" userData={{ name: "g Group4" }}>
          <mesh
            name="Group4"
            castShadow
            receiveShadow
            geometry={nodes.Group4.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group4" }}
          />
        </group>
        <group name="g_Group5" userData={{ name: "g Group5" }}>
          <mesh
            name="Group5"
            castShadow
            receiveShadow
            geometry={nodes.Group5.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group5" }}
          />
        </group>
        <group name="g_Group6" userData={{ name: "g Group6" }}>
          <mesh
            name="Group6"
            castShadow
            receiveShadow
            geometry={nodes.Group6.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group6" }}
          />
        </group>
        <group name="g_Group61531" userData={{ name: "g Group61531" }}>
          <mesh
            name="Group61531"
            castShadow
            receiveShadow
            geometry={nodes.Group61531.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group61531" }}
          />
        </group>
        <group name="g_Group7" userData={{ name: "g Group7" }}>
          <mesh
            name="Group7"
            castShadow
            receiveShadow
            geometry={nodes.Group7.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group7" }}
          />
        </group>
        <group name="g_Group8" userData={{ name: "g Group8" }}>
          <mesh
            name="Group8"
            castShadow
            receiveShadow
            geometry={nodes.Group8.geometry}
            material={materials.lambert112SG}
            userData={{ name: "Group8" }}
          />
        </group>
        <group
          name="g_ZBrush_defualt_group"
          userData={{ name: "g ZBrush_defualt_group" }}
        >
          <mesh
            name="ZBrush_defualt_group"
            castShadow
            receiveShadow
            geometry={nodes.ZBrush_defualt_group.geometry}
            material={materials.lambert112SG}
            userData={{ name: "ZBrush_defualt_group" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/silla.gltf");
