/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _Group10: THREE.Mesh;
    _Group2: THREE.Mesh;
    _Group3: THREE.Mesh;
    _Group4: THREE.Mesh;
    _Group5: THREE.Mesh;
    _Group6: THREE.Mesh;
    _Group7: THREE.Mesh;
    _Group8: THREE.Mesh;
    _Group9: THREE.Mesh;
    Group10: THREE.Mesh;
    Group11: THREE.Mesh;
    Group12: THREE.Mesh;
    Group13: THREE.Mesh;
    Group14: THREE.Mesh;
    Group15: THREE.Mesh;
    Group16: THREE.Mesh;
    Group17: THREE.Mesh;
    Group18: THREE.Mesh;
    Group19: THREE.Mesh;
    Group2: THREE.Mesh;
    Group20: THREE.Mesh;
    Group21: THREE.Mesh;
    Group22: THREE.Mesh;
    Group23: THREE.Mesh;
    Group24: THREE.Mesh;
    Group25: THREE.Mesh;
    Group26: THREE.Mesh;
    Group28: THREE.Mesh;
    Group29: THREE.Mesh;
    Group3: THREE.Mesh;
    Group30: THREE.Mesh;
    Group31: THREE.Mesh;
    Group32: THREE.Mesh;
    Group33: THREE.Mesh;
    Group34: THREE.Mesh;
    Group35: THREE.Mesh;
    Group4: THREE.Mesh;
    Group5: THREE.Mesh;
    Group6: THREE.Mesh;
    Group61531: THREE.Mesh;
    Group7: THREE.Mesh;
    Group8: THREE.Mesh;
    ZBrush_defualt_group: THREE.Mesh;
    round_carpet: THREE.Mesh;
  };
  materials: {
    lambert112SG: THREE.MeshPhysicalMaterial;
    ["round carpet"]: THREE.MeshStandardMaterial;
  };
};

export function ModelChair(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/silla.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        name="_Group10"
        castShadow
        receiveShadow
        geometry={nodes._Group10.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group2"
        castShadow
        receiveShadow
        geometry={nodes._Group2.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group3"
        castShadow
        receiveShadow
        geometry={nodes._Group3.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group4"
        castShadow
        receiveShadow
        geometry={nodes._Group4.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group5"
        castShadow
        receiveShadow
        geometry={nodes._Group5.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group6"
        castShadow
        receiveShadow
        geometry={nodes._Group6.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group7"
        castShadow
        receiveShadow
        geometry={nodes._Group7.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group8"
        castShadow
        receiveShadow
        geometry={nodes._Group8.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="_Group9"
        castShadow
        receiveShadow
        geometry={nodes._Group9.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group10"
        castShadow
        receiveShadow
        geometry={nodes.Group10.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group11"
        castShadow
        receiveShadow
        geometry={nodes.Group11.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group12"
        castShadow
        receiveShadow
        geometry={nodes.Group12.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group13"
        castShadow
        receiveShadow
        geometry={nodes.Group13.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group14"
        castShadow
        receiveShadow
        geometry={nodes.Group14.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group15"
        castShadow
        receiveShadow
        geometry={nodes.Group15.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group16"
        castShadow
        receiveShadow
        geometry={nodes.Group16.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group17"
        castShadow
        receiveShadow
        geometry={nodes.Group17.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group18"
        castShadow
        receiveShadow
        geometry={nodes.Group18.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group19"
        castShadow
        receiveShadow
        geometry={nodes.Group19.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group2"
        castShadow
        receiveShadow
        geometry={nodes.Group2.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group20"
        castShadow
        receiveShadow
        geometry={nodes.Group20.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group21"
        castShadow
        receiveShadow
        geometry={nodes.Group21.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group22"
        castShadow
        receiveShadow
        geometry={nodes.Group22.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group23"
        castShadow
        receiveShadow
        geometry={nodes.Group23.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group24"
        castShadow
        receiveShadow
        geometry={nodes.Group24.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group25"
        castShadow
        receiveShadow
        geometry={nodes.Group25.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group26"
        castShadow
        receiveShadow
        geometry={nodes.Group26.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group28"
        castShadow
        receiveShadow
        geometry={nodes.Group28.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group29"
        castShadow
        receiveShadow
        geometry={nodes.Group29.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group3"
        castShadow
        receiveShadow
        geometry={nodes.Group3.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group30"
        castShadow
        receiveShadow
        geometry={nodes.Group30.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group31"
        castShadow
        receiveShadow
        geometry={nodes.Group31.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group32"
        castShadow
        receiveShadow
        geometry={nodes.Group32.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group33"
        castShadow
        receiveShadow
        geometry={nodes.Group33.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group34"
        castShadow
        receiveShadow
        geometry={nodes.Group34.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group35"
        castShadow
        receiveShadow
        geometry={nodes.Group35.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group4"
        castShadow
        receiveShadow
        geometry={nodes.Group4.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group5"
        castShadow
        receiveShadow
        geometry={nodes.Group5.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group6"
        castShadow
        receiveShadow
        geometry={nodes.Group6.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group61531"
        castShadow
        receiveShadow
        geometry={nodes.Group61531.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group7"
        castShadow
        receiveShadow
        geometry={nodes.Group7.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="Group8"
        castShadow
        receiveShadow
        geometry={nodes.Group8.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="ZBrush_defualt_group"
        castShadow
        receiveShadow
        geometry={nodes.ZBrush_defualt_group.geometry}
        material={materials.lambert112SG}
      />
      <mesh
        name="round_carpet"
        castShadow
        receiveShadow
        geometry={nodes.round_carpet.geometry}
        material={materials["round carpet"]}
      />
    </group>
  );
}

useGLTF.preload("/models/silla.gltf");
