/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ModelEscritorio(props: any) {
  const { nodes, materials }: any = useGLTF("/models3D/escritorio.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[2.76907086, 0.65455389, 0.94157887]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex.geometry}
          material={materials.screen_phone_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_1.geometry}
          material={materials.iphone_11_max_pro}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_2.geometry}
          material={materials.base_phone}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_3.geometry}
          material={materials.screen_monitor_material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_4.geometry}
          material={materials.monitor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_5.geometry}
          material={materials["teclado.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_6.geometry}
          material={materials.frontal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_7.geometry}
          material={materials.demas}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_8.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_9.geometry}
          material={materials.wire_000000083}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_10.geometry}
          material={materials.wire_169255193}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.escritorio_hex_11.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models3D/escritorio.gltf");
