/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Image from "next/image";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Malla029: THREE.Mesh;
    Malla029_1: THREE.Mesh;
    ["7_obj(3001852)"]: THREE.Mesh;
    ["9_obj(3001852)"]: THREE.Mesh;
    Malla038: THREE.Mesh;
    Malla038_1: THREE.Mesh;
    ["7_obj(3001852)001"]: THREE.Mesh;
    ["9_obj(3001852)001"]: THREE.Mesh;
    B: THREE.Mesh;
    A: THREE.Mesh;
    Object003: THREE.Mesh;
    Malla019: THREE.Mesh;
    Malla019_1: THREE.Mesh;
    TV서람장_위_선반: THREE.Mesh;
    Object001: THREE.Mesh;
    Object004: THREE.Mesh;
    Malla022: THREE.Mesh;
    Malla022_1: THREE.Mesh;
    ["2_obj(3001852)"]: THREE.Mesh;
    ["10_obj(3001852)"]: THREE.Mesh;
    Malla031: THREE.Mesh;
    Malla031_1: THREE.Mesh;
    ["2_obj(3001852)001"]: THREE.Mesh;
    ["10_obj(3001852)001"]: THREE.Mesh;
    Monitor: THREE.Mesh;
    MouseThermaltakeBlack_1: THREE.Mesh;
    MouseThermaltakeBlack_2: THREE.Mesh;
    MouseThermaltakeBlack_3: THREE.Mesh;
    MouseThermaltakeBlack_4: THREE.Mesh;
    MouseThermaltakeBlack_5: THREE.Mesh;
    MouseThermaltakeBlack_6: THREE.Mesh;
    MouseThermaltakeBlack_7: THREE.Mesh;
    MouseThermaltakeBlack_8: THREE.Mesh;
    Light_Desktop: THREE.Mesh;
    iphone_11_max_pro: THREE.Mesh;
    Light001: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube004_1: THREE.Mesh;
    Cube004_2: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube006_1: THREE.Mesh;
    Cube006_2: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Industrial_Fan_1001_Cube011_1: THREE.Mesh;
    Industrial_Fan_1001_Cube011_2: THREE.Mesh;
    Industrial_Fan_1002_Cube012_1: THREE.Mesh;
    Industrial_Fan_1002_Cube012_2: THREE.Mesh;
    Industrial_Fan_1003_Cube013_1: THREE.Mesh;
    Industrial_Fan_1003_Cube013_2: THREE.Mesh;
    Industrial_Fan_1_Cube009_1: THREE.Mesh;
    Industrial_Fan_1_Cube009_2: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane002_Plane007: THREE.Mesh;
    Plane003_Plane008: THREE.Mesh;
    Plane004_Plane009: THREE.Mesh;
    Plane005_Plane010: THREE.Mesh;
    Plane006_Plane011: THREE.Mesh;
    Plane007_Plane002: THREE.Mesh;
    Malla005: THREE.Mesh;
    Malla005_1: THREE.Mesh;
    Malla005_2: THREE.Mesh;
    Malla005_3: THREE.Mesh;
    Malla005_4: THREE.Mesh;
    Malla005_5: THREE.Mesh;
    Audifonnos_1: THREE.Mesh;
    Audifonnos_2: THREE.Mesh;
    Audifonnos_3: THREE.Mesh;
    Audifonnos_4: THREE.Mesh;
    Audifonnos_5: THREE.Mesh;
    Audifonnos_6: THREE.Mesh;
    Audifonnos_7: THREE.Mesh;
    Audifonnos_8: THREE.Mesh;
    Audifonnos_9: THREE.Mesh;
    Base: THREE.Mesh;
    AV: THREE.Mesh;
    AV002: THREE.Mesh;
    Body: THREE.Mesh;
    HDMIPORT001: THREE.Mesh;
    HDMIPORT002: THREE.Mesh;
    Service: THREE.Mesh;
    Base001: THREE.Mesh;
    Base002: THREE.Mesh;
    Mode: THREE.Mesh;
    Power: THREE.Mesh;
    PowerIndicator: THREE.Mesh;
    Rectangle001: THREE.Mesh;
    Rectangle002: THREE.Mesh;
    VolumeDOWN: THREE.Mesh;
    VolumeUp: THREE.Mesh;
    WifiSignalIndicator: THREE.Mesh;
    Imagen_Celular: THREE.Mesh;
    ["keyboard_us-compact-horizontalobj"]: THREE.Mesh;
    Screen: THREE.Mesh;
    Display: THREE.Mesh;
    Cube001_Cube_1: THREE.Mesh;
    Cube001_Cube_2: THREE.Mesh;
    Cube_Cube001_1: THREE.Mesh;
    Cube_Cube001_2: THREE.Mesh;
    Cube_Cube001_3: THREE.Mesh;
    Suelo: THREE.Mesh;
    Pata_Izquierda_Escritorio: THREE.Mesh;
    Pata_Izquierda_Escritorio_1: THREE.Mesh;
    Pata_Izquierda_Escritorio_2: THREE.Mesh;
    Pata_Izquierda_Escritorio_3: THREE.Mesh;
    Pata_Derecha_Escritorio: THREE.Mesh;
    Pata_Derecha_Escritorio_1: THREE.Mesh;
    Pata_Derecha_Escritorio_2: THREE.Mesh;
    Pata_Derecha_Escritorio_3: THREE.Mesh;
    table_top: THREE.Mesh;
    Base_de_Escritorio: THREE.Mesh;
    Base_de_Escritorio_1: THREE.Mesh;
    Base_de_Escritorio_2: THREE.Mesh;
    Ventana_1: THREE.Mesh;
    Ventana_2: THREE.Mesh;
    Ventana_3: THREE.Mesh;
    Ventana_4: THREE.Mesh;
    Ventana_5: THREE.Mesh;
    Ventana_6: THREE.Mesh;
    Mesh_Default_0: THREE.Mesh;
    Mesh_Default_0_1: THREE.Mesh;
    Pared_Derecha: THREE.Mesh;
    Pared_Principal: THREE.Mesh;
    Couch: THREE.Mesh;
  };
  materials: {
    ["27_mat(3001852).002"]: THREE.MeshStandardMaterial;
    ["28_mat(3001852).002"]: THREE.MeshStandardMaterial;
    ["32_mat(3001852).002"]: THREE.MeshStandardMaterial;
    ["31_mat(3001852).002"]: THREE.MeshStandardMaterial;
    ["27_mat(3001852).003"]: THREE.MeshStandardMaterial;
    ["28_mat(3001852).003"]: THREE.MeshStandardMaterial;
    ["32_mat(3001852).003"]: THREE.MeshStandardMaterial;
    ["31_mat(3001852).003"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    Ceramic: THREE.MeshStandardMaterial;
    ["03 - Default"]: THREE.MeshStandardMaterial;
    ["04 - Default"]: THREE.MeshStandardMaterial;
    ["27_mat(3001852).001"]: THREE.MeshStandardMaterial;
    ["28_mat(3001852)"]: THREE.MeshStandardMaterial;
    ["32_mat(3001852)"]: THREE.MeshStandardMaterial;
    ["31_mat(3001852)"]: THREE.MeshStandardMaterial;
    ["27_mat(3001852).004"]: THREE.MeshStandardMaterial;
    ["28_mat(3001852).001"]: THREE.MeshStandardMaterial;
    ["32_mat(3001852).001"]: THREE.MeshStandardMaterial;
    ["31_mat(3001852).001"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    wire_000000083: THREE.MeshPhysicalMaterial;
    wire_000000125: THREE.MeshPhysicalMaterial;
    wire_169255193: THREE.MeshPhysicalMaterial;
    wire_000083069: THREE.MeshPhysicalMaterial;
    wire_197131131: THREE.MeshPhysicalMaterial;
    wire_083035000: THREE.MeshPhysicalMaterial;
    wire_000083000: THREE.MeshPhysicalMaterial;
    wire_255215169: THREE.MeshPhysicalMaterial;
    ["Light Light Desktop"]: THREE.MeshStandardMaterial;
    iphone_11_max_pro: THREE.MeshPhysicalMaterial;
    ["Light.001"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["klothh_XSIPOLYCLS.klothh_material"]: THREE.MeshStandardMaterial;
    ["Default_XSIPOLYCLS.default_material"]: THREE.MeshStandardMaterial;
    ["syhh_XSIPOLYCLS.syhh_material"]: THREE.MeshStandardMaterial;
    ["logoo_XSIPOLYCLS.logoo_material"]: THREE.MeshStandardMaterial;
    ["metalikkplastik_XSIPOLYCLS.metalikkplastik_material"]: THREE.MeshStandardMaterial;
    ["yazilar_XSIPOLYCLS.yazilar_material"]: THREE.MeshStandardMaterial;
    blinn1: THREE.MeshStandardMaterial;
    blinn2: THREE.MeshStandardMaterial;
    blinn3: THREE.MeshStandardMaterial;
    kulaklik_pilastik1_file4: THREE.MeshStandardMaterial;
    kulaklik_pilastik2: THREE.MeshStandardMaterial;
    kulaklik_pilastik: THREE.MeshStandardMaterial;
    blinn5: THREE.MeshStandardMaterial;
    metal: THREE.MeshStandardMaterial;
    ["kulaklik_pilastik1_file4.001"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    wire_204204204: THREE.MeshStandardMaterial;
    wire_088144225: THREE.MeshStandardMaterial;
    ["Imagen Celular"]: THREE.MeshStandardMaterial;
    ["Default.002"]: THREE.MeshPhysicalMaterial;
    Screen: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshBasicMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    Suelo: THREE.MeshPhysicalMaterial;
    ["paint RAL 7035"]: THREE.MeshStandardMaterial;
    ["paint black"]: THREE.MeshStandardMaterial;
    steel: THREE.MeshStandardMaterial;
    ["plastic black"]: THREE.MeshStandardMaterial;
    Vidrios: THREE.MeshStandardMaterial;
    glass_border1: THREE.MeshStandardMaterial;
    handle: THREE.MeshStandardMaterial;
    window1: THREE.MeshStandardMaterial;
    window2: THREE.MeshStandardMaterial;
    sill: THREE.MeshStandardMaterial;
    clock: THREE.MeshStandardMaterial;
    ["Prism Glass.001"]: THREE.MeshStandardMaterial;
    ["Pared Derecha"]: THREE.MeshPhysicalMaterial;
    ["Pared Principal"]: THREE.MeshPhysicalMaterial;
    Chocofur_Fabric_Solid_20: THREE.MeshStandardMaterial;
  };
};

export function Model(props: any) {
  const { OnclickLight, OnclickLight2, OnclickLight3 } = props;
  const { nodes, materials } = useGLTF("/models/Office.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="Planta_IZQUIERDA"
        position={[-0.16515729, 0.62202436, 0.45684993]}
        rotation={[-Math.PI, 0.08726613, -Math.PI]}
        scale={0.001}
      >
        <group
          name="4_obj(3001852)"
          position={[2242.51123047, 1829.61291504, 3059.77368164]}
          scale={[0.56826615, 0.56826627, 0.56826615]}
        >
          <mesh
            name="Malla029"
            castShadow
            receiveShadow
            geometry={nodes.Malla029.geometry}
            material={materials["27_mat(3001852).002"]}
          />
          <mesh
            name="Malla029_1"
            castShadow
            receiveShadow
            geometry={nodes.Malla029_1.geometry}
            material={materials["28_mat(3001852).002"]}
          />
        </group>
        <mesh
          name="7_obj(3001852)"
          castShadow
          receiveShadow
          geometry={nodes["7_obj(3001852)"].geometry}
          material={materials["32_mat(3001852).002"]}
          position={[2239.56762695, 1985.08435059, 3060.93847656]}
          scale={[0.56826609, 0.56826627, 0.56826609]}
        />
        <mesh
          name="9_obj(3001852)"
          castShadow
          receiveShadow
          geometry={nodes["9_obj(3001852)"].geometry}
          material={materials["31_mat(3001852).002"]}
          position={[2242.63085938, 1919.96350098, 3059.17431641]}
          scale={[0.56826615, 0.56826627, 0.56826615]}
        />
      </group>
      <group
        name="Planta_DERECHA"
        position={[1.10997975, 0.55907202, 0.45684993]}
        rotation={[-Math.PI, 0.08726613, -Math.PI]}
        scale={0.001}
      >
        <group
          name="4_obj(3001852)001"
          position={[2155.36621094, 1891.53637695, 3067.39770508]}
          scale={[0.56826615, 0.56826627, 0.56826615]}
        >
          <mesh
            name="Malla038"
            castShadow
            receiveShadow
            geometry={nodes.Malla038.geometry}
            material={materials["27_mat(3001852).003"]}
          />
          <mesh
            name="Malla038_1"
            castShadow
            receiveShadow
            geometry={nodes.Malla038_1.geometry}
            material={materials["28_mat(3001852).003"]}
          />
        </group>
        <mesh
          name="7_obj(3001852)001"
          castShadow
          receiveShadow
          geometry={nodes["7_obj(3001852)001"].geometry}
          material={materials["32_mat(3001852).003"]}
          position={[2152.42236328, 2047.0078125, 3068.56201172]}
          scale={[0.56826609, 0.56826627, 0.56826609]}
        />
        <mesh
          name="9_obj(3001852)001"
          castShadow
          receiveShadow
          geometry={nodes["9_obj(3001852)001"].geometry}
          material={materials["31_mat(3001852).003"]}
          position={[2155.48510742, 1981.88793945, 3066.79833984]}
          scale={[0.56826615, 0.56826627, 0.56826615]}
        />
      </group>
      <group
        name="AB"
        position={[-2.42281342, 0.92095798, -2.1595881]}
        rotation={[1.4083013, 0.08542269, -0.46200764]}
        scale={0.01225855}
      >
        <mesh
          name="B"
          castShadow
          receiveShadow
          geometry={nodes.B.geometry}
          material={materials["Material.008"]}
          position={[-0.12177017, 2.31928921, -2.82950211]}
          rotation={[-0.18202791, 0.04705288, 0.00162851]}
        />
        <mesh
          name="A"
          castShadow
          receiveShadow
          geometry={nodes.A.geometry}
          material={materials["Material.009"]}
          position={[0.03961527, 0.01437092, -0.00000572]}
        />
      </group>
      <group
        name="a_TV_drawer"
        position={[3.15663075, 0.2319867, 0.94850343]}
        rotation={[3.00222836, -1.56732258, 3.00152313]}
        scale={0.00676902}
      >
        <mesh
          name="Object003"
          castShadow
          receiveShadow
          geometry={nodes.Object003.geometry}
          material={materials.Ceramic}
          position={[4.20208216, -6.49949312, 31.44262314]}
          scale={[0.98633862, 1, 1.47379231]}
        />
        <group
          name="Box001"
          position={[0.02026834, -17.12040329, 8.70806217]}
          scale={[1, 1, 1.47379231]}
        >
          <mesh
            name="Malla019"
            castShadow
            receiveShadow
            geometry={nodes.Malla019.geometry}
            material={materials["03 - Default"]}
          />
          <mesh
            name="Malla019_1"
            castShadow
            receiveShadow
            geometry={nodes.Malla019_1.geometry}
            material={materials.Ceramic}
          />
        </group>
        <mesh
          name="TV서람장_위_선반"
          castShadow
          receiveShadow
          geometry={nodes.TV서람장_위_선반.geometry}
          material={materials["03 - Default"]}
          position={[-5.92167568, 21.17464447, -1.4280746]}
        />
        <mesh
          name="Object001"
          castShadow
          receiveShadow
          geometry={nodes.Object001.geometry}
          material={materials["04 - Default"]}
          position={[-0.00002621, 8.33013821, -2.17254186]}
          scale={[1, 1, 1.47379231]}
        />
        <mesh
          name="Object004"
          castShadow
          receiveShadow
          geometry={nodes.Object004.geometry}
          material={materials["04 - Default"]}
          position={[-4.38107109, 33.37192917, -1.1796813]}
        />
      </group>
      <group
        name="Planta_dERECHA"
        position={[3.14912558, 0.28704181, 1.57825708]}
        rotation={[0, -0.09855866, 0]}
        scale={0.00115129}
      >
        <group
          name="3_obj(3001852)"
          position={[56.08985901, 141.84672546, 535.09179688]}
          scale={[0.5553751, 0.55537516, 0.5553751]}
        >
          <mesh
            name="Malla022"
            castShadow
            receiveShadow
            geometry={nodes.Malla022.geometry}
            material={materials["27_mat(3001852).001"]}
          />
          <mesh
            name="Malla022_1"
            castShadow
            receiveShadow
            geometry={nodes.Malla022_1.geometry}
            material={materials["28_mat(3001852)"]}
          />
        </group>
        <mesh
          name="2_obj(3001852)"
          castShadow
          receiveShadow
          geometry={nodes["2_obj(3001852)"].geometry}
          material={materials["32_mat(3001852)"]}
          position={[52.72173691, 370.52328491, 530.05487061]}
          scale={[0.5553751, 0.55537516, 0.5553751]}
        />
        <mesh
          name="10_obj(3001852)"
          castShadow
          receiveShadow
          geometry={nodes["10_obj(3001852)"].geometry}
          material={materials["31_mat(3001852)"]}
          position={[55.94369125, 271.30160522, 535.8425293]}
          scale={[0.5553751, 0.55537516, 0.5553751]}
        />
      </group>
      <group
        name="Planta_IZQUIERDA001"
        position={[3.16553712, 0.29169318, -1.00835359]}
        rotation={[0, -0.0933585, 0]}
        scale={0.00115129}
      >
        <group
          name="3_obj(3001852)001"
          position={[64.80093384, 141.84672546, 539.50970459]}
          rotation={[0, -0.00520014, 0]}
          scale={0.55537516}
        >
          <mesh
            name="Malla031"
            castShadow
            receiveShadow
            geometry={nodes.Malla031.geometry}
            material={materials["27_mat(3001852).004"]}
          />
          <mesh
            name="Malla031_1"
            castShadow
            receiveShadow
            geometry={nodes.Malla031_1.geometry}
            material={materials["28_mat(3001852).001"]}
          />
        </group>
        <mesh
          name="2_obj(3001852)001"
          castShadow
          receiveShadow
          geometry={nodes["2_obj(3001852)001"].geometry}
          material={materials["32_mat(3001852).001"]}
          position={[61.45827484, 370.52325439, 534.4553833]}
          rotation={[0, -0.00519997, 0]}
          scale={0.55537516}
        />
        <mesh
          name="10_obj(3001852)001"
          castShadow
          receiveShadow
          geometry={nodes["10_obj(3001852)001"].geometry}
          material={materials["31_mat(3001852).001"]}
          position={[64.65048981, 271.30160522, 540.25976563]}
          rotation={[0, -0.00520014, 0]}
          scale={0.55537516}
        />
      </group>
      <mesh
        name="Monitor"
        castShadow
        receiveShadow
        geometry={nodes.Monitor.geometry}
        material={materials["Material.013"]}
        position={[-1.76530588, 1.28978753, -2.79085135]}
        rotation={[0.91840821, -1.56644812, 0.9604288]}
        scale={[0.02307017, 0.39398289, 0.78841311]}
      >
        <Html
          scale={0.03}
          rotation={[0.91840821, -1.56644812, 0.9604288]}
          position={[5, 2, -0.38]}
          transform
          occlude
        >
          <Image
            src="/images/points/info.png"
            width={400}
            height={1150}
            alt={""}
          />
        </Html>
      </mesh>
      <group
        name="MouseThermaltakeBlack"
        position={[-0.89901114, 0.92891216, -2.21570635]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.04708813}
      >
        <mesh
          name="MouseThermaltakeBlack_1"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_1.geometry}
          material={materials.wire_000000083}
        />
        <mesh
          name="MouseThermaltakeBlack_2"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_2.geometry}
          material={materials.wire_000000125}
        />
        <mesh
          name="MouseThermaltakeBlack_3"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_3.geometry}
          material={materials.wire_169255193}
        />
        <mesh
          name="MouseThermaltakeBlack_4"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_4.geometry}
          material={materials.wire_000083069}
        />
        <mesh
          name="MouseThermaltakeBlack_5"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_5.geometry}
          material={materials.wire_197131131}
        />
        <mesh
          name="MouseThermaltakeBlack_6"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_6.geometry}
          material={materials.wire_083035000}
        />
        <mesh
          name="MouseThermaltakeBlack_7"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_7.geometry}
          material={materials.wire_000083000}
        />
        <mesh
          name="MouseThermaltakeBlack_8"
          castShadow
          receiveShadow
          geometry={nodes.MouseThermaltakeBlack_8.geometry}
          material={materials.wire_255215169}
        />
      </group>
      <mesh
        name="Light_Desktop"
        castShadow
        receiveShadow
        geometry={nodes.Light_Desktop.geometry}
        material={materials["Light Light Desktop"]}
        position={[-1.54568839, 2.8064177, -2.98424625]}
        scale={0.38639081}
        onPointerEnter={OnclickLight3}
      />
      <mesh
        name="iphone_11_max_pro"
        castShadow
        receiveShadow
        geometry={nodes.iphone_11_max_pro.geometry}
        material={materials.iphone_11_max_pro}
        position={[-2.42180967, 1.10505962, -2.19706225]}
        rotation={[1.17908962, 0.19823378, 1.4014055]}
        scale={0.00182099}
      />
      <mesh
        name="Light001"
        castShadow
        receiveShadow
        geometry={nodes.Light001.geometry}
        material={materials["Light.001"]}
        position={[3.4418757, 2.93796015, 1.21835959]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.38639081}
        onPointerEnter={OnclickLight2}
      />
      <mesh
        name="Cube002"
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material.001"]}
        position={[0.11554891, 0.3389467, -2.25635934]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Cube003"
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[0.099567, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <group
        name="Cube004"
        position={[0.09956706, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube004_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube004_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube004_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        name="Cube005"
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube001_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        name="Cube006"
        position={[0.099567, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube006_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube006_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        name="Cube007"
        position={[0.099567, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube007_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube007_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        name="Cube008"
        position={[0.099567, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube008_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube008_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube008_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube008_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <group
        name="Industrial_Fan_1001_Cube011"
        position={[0.09956706, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Industrial_Fan_1001_Cube011_1"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1001_Cube011_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Industrial_Fan_1001_Cube011_2"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1001_Cube011_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        name="Industrial_Fan_1002_Cube012"
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Industrial_Fan_1002_Cube012_1"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1002_Cube012_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Industrial_Fan_1002_Cube012_2"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1002_Cube012_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        name="Industrial_Fan_1003_Cube013"
        position={[0.09956706, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Industrial_Fan_1003_Cube013_1"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1003_Cube013_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Industrial_Fan_1003_Cube013_2"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1003_Cube013_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <group
        name="Industrial_Fan_1_Cube009"
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Industrial_Fan_1_Cube009_1"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1_Cube009_1.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Industrial_Fan_1_Cube009_2"
          castShadow
          receiveShadow
          geometry={nodes.Industrial_Fan_1_Cube009_2.geometry}
          material={materials["Material.001"]}
        />
      </group>
      <mesh
        name="Plane001"
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane002_Plane007"
        castShadow
        receiveShadow
        geometry={nodes.Plane002_Plane007.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane003_Plane008"
        castShadow
        receiveShadow
        geometry={nodes.Plane003_Plane008.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane004_Plane009"
        castShadow
        receiveShadow
        geometry={nodes.Plane004_Plane009.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.33894664, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane005_Plane010"
        castShadow
        receiveShadow
        geometry={nodes.Plane005_Plane010.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane006_Plane011"
        castShadow
        receiveShadow
        geometry={nodes.Plane006_Plane011.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.3389467, -2.31684852]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      />
      <mesh
        name="Plane007_Plane002"
        castShadow
        receiveShadow
        geometry={nodes.Plane007_Plane002.geometry}
        material={materials["Material.001"]}
        position={[0.09956706, 0.33894664, -2.51754951]}
        rotation={[Math.PI / 2, 6e-8, Math.PI / 2]}
        scale={0.15443034}
      />
      <group
        name="objpolymsh_detached4"
        position={[-1.45573938, 1.0917182, -2.76571321]}
        scale={0.01988596}
      >
        <mesh
          name="Malla005"
          castShadow
          receiveShadow
          geometry={nodes.Malla005.geometry}
          material={materials["klothh_XSIPOLYCLS.klothh_material"]}
        />
        <mesh
          name="Malla005_1"
          castShadow
          receiveShadow
          geometry={nodes.Malla005_1.geometry}
          material={materials["Default_XSIPOLYCLS.default_material"]}
        />
        <mesh
          name="Malla005_2"
          castShadow
          receiveShadow
          geometry={nodes.Malla005_2.geometry}
          material={materials["syhh_XSIPOLYCLS.syhh_material"]}
        />
        <mesh
          name="Malla005_3"
          castShadow
          receiveShadow
          geometry={nodes.Malla005_3.geometry}
          material={materials["logoo_XSIPOLYCLS.logoo_material"]}
        />
        <mesh
          name="Malla005_4"
          castShadow
          receiveShadow
          geometry={nodes.Malla005_4.geometry}
          material={
            materials["metalikkplastik_XSIPOLYCLS.metalikkplastik_material"]
          }
        />
        <mesh
          name="Malla005_5"
          castShadow
          receiveShadow
          geometry={nodes.Malla005_5.geometry}
          material={materials["yazilar_XSIPOLYCLS.yazilar_material"]}
        />
      </group>
      <group
        name="Audifonnos"
        position={[-2.86717892, 0.77251679, -2.07553864]}
        rotation={[1.56955677, -0.09349355, 3.12828619]}
        scale={[0.2659969, 0.26599684, 0.26599681]}
      >
        <mesh
          name="Audifonnos_1"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_1.geometry}
          material={materials.blinn1}
        />
        <mesh
          name="Audifonnos_2"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_2.geometry}
          material={materials.blinn2}
        />
        <mesh
          name="Audifonnos_3"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_3.geometry}
          material={materials.blinn3}
        />
        <mesh
          name="Audifonnos_4"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_4.geometry}
          material={materials.kulaklik_pilastik1_file4}
        />
        <mesh
          name="Audifonnos_5"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_5.geometry}
          material={materials.kulaklik_pilastik2}
        />
        <mesh
          name="Audifonnos_6"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_6.geometry}
          material={materials.kulaklik_pilastik}
        />
        <mesh
          name="Audifonnos_7"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_7.geometry}
          material={materials.blinn5}
        />
        <mesh
          name="Audifonnos_8"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_8.geometry}
          material={materials.metal}
        />
        <mesh
          name="Audifonnos_9"
          castShadow
          receiveShadow
          geometry={nodes.Audifonnos_9.geometry}
          material={materials["kulaklik_pilastik1_file4.001"]}
        />
      </group>
      <mesh
        name="Base"
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
        material={materials["Material.005"]}
        position={[-1.41257477, 0.9926523, -2.73376513]}
        rotation={[2.58550029, -1.56816618, 2.6274906]}
        scale={0.02307017}
      />
      <mesh
        name="AV"
        castShadow
        receiveShadow
        geometry={nodes.AV.geometry}
        material={materials.wire_204204204}
        position={[3.20292616, 0.94707954, 1.02544153]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="AV002"
        castShadow
        receiveShadow
        geometry={nodes.AV002.geometry}
        material={materials.wire_204204204}
        position={[3.20291233, 0.96163571, 1.02552962]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Body"
        castShadow
        receiveShadow
        geometry={nodes.Body.geometry}
        material={materials.wire_204204204}
        position={[3.18473864, 0.81970417, 0.90431863]}
        rotation={[Math.PI / 2, 0, -3.14055044]}
        scale={0.00974252}
      />
      <mesh
        name="HDMIPORT001"
        castShadow
        receiveShadow
        geometry={nodes.HDMIPORT001.geometry}
        material={materials.wire_204204204}
        position={[3.20224643, 0.91938293, 1.02632725]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="HDMIPORT002"
        castShadow
        receiveShadow
        geometry={nodes.HDMIPORT002.geometry}
        material={materials.wire_204204204}
        position={[3.20224643, 0.90872037, 1.02632725]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Service"
        castShadow
        receiveShadow
        geometry={nodes.Service.geometry}
        material={materials.wire_204204204}
        position={[3.20250487, 0.89084226, 1.02725244]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Base001"
        castShadow
        receiveShadow
        geometry={nodes.Base001.geometry}
        material={materials.wire_088144225}
        position={[3.14933252, 0.54410923, 1.4388684]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Base002"
        castShadow
        receiveShadow
        geometry={nodes.Base002.geometry}
        material={materials.wire_088144225}
        position={[3.17283297, 0.54510957, 0.38588879]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Mode"
        castShadow
        receiveShadow
        geometry={nodes.Mode.geometry}
        material={materials.wire_088144225}
        position={[3.13706493, 0.63197827, 1.64664805]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Power"
        castShadow
        receiveShadow
        geometry={nodes.Power.geometry}
        material={materials.wire_088144225}
        position={[3.137187, 0.61680871, 1.6469928]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="PowerIndicator"
        castShadow
        receiveShadow
        geometry={nodes.PowerIndicator.geometry}
        material={materials.wire_088144225}
        position={[3.14888573, 0.58622551, 0.89725775]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Rectangle001"
        castShadow
        receiveShadow
        geometry={nodes.Rectangle001.geometry}
        material={materials.wire_088144225}
        position={[3.1464231, 0.61163211, 1.43811357]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Rectangle002"
        castShadow
        receiveShadow
        geometry={nodes.Rectangle002.geometry}
        material={materials.wire_088144225}
        position={[3.16990709, 0.60862893, 0.38590237]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="VolumeDOWN"
        castShadow
        receiveShadow
        geometry={nodes.VolumeDOWN.geometry}
        material={materials.wire_088144225}
        position={[3.13716125, 0.66644871, 1.6466887]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="VolumeUp"
        castShadow
        receiveShadow
        geometry={nodes.VolumeUp.geometry}
        material={materials.wire_088144225}
        position={[3.13715529, 0.64877427, 1.6466943]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="WifiSignalIndicator"
        castShadow
        receiveShadow
        geometry={nodes.WifiSignalIndicator.geometry}
        material={materials.wire_088144225}
        position={[3.14800692, 0.58367366, 0.92562467]}
        rotation={[Math.PI / 2, 0, -3.13029987]}
        scale={0.00974252}
      />
      <mesh
        name="Imagen_Celular"
        castShadow
        receiveShadow
        geometry={nodes.Imagen_Celular.geometry}
        material={materials["Imagen Celular"]}
        position={[-2.42077351, 1.05317926, -2.15202904]}
        rotation={[1.18318301, 0.20044533, -0.43508243]}
        scale={[0.06178416, 0.12154189, 0.12154189]}
      >
        <Html
          scale={0.1}
          rotation={[Math.PI / -2.6, -0.95, -0.01]}
          position={[0, 0.5, -3]}
          transform
          occlude
        >
          <Image
            src="/images/points/info.png"
            width={750}
            height={1000}
            alt={""}
          />
        </Html>
      </mesh>
      <mesh
        name="keyboard_us-compact-horizontalobj"
        castShadow
        receiveShadow
        geometry={nodes["keyboard_us-compact-horizontalobj"].geometry}
        material={materials["Default.002"]}
        position={[-1.44663501, 0.92610794, -2.21534276]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.87483728}
      />
      <mesh
        name="Screen"
        castShadow
        receiveShadow
        geometry={nodes.Screen.geometry}
        material={materials.Screen}
        position={[-1.42244303, 1.47858882, -2.68391061]}
        rotation={[0.31846728, -1.54327825, 0.36068579]}
        scale={[0.02307017, 0.39398283, 0.78841311]}
      />
      <mesh
        name="Display"
        castShadow
        receiveShadow
        geometry={nodes.Display.geometry}
        material={materials["Material.011"]}
        position={[3.14259982, 1.04286575, 0.90059954]}
        rotation={[Math.PI / 2, 0, -3.14055044]}
        scale={0.00974252}
      />
      <group
        name="Cube001_Cube"
        position={[0.09828436, 0.3389467, -2.71468377]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube001_Cube_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube001_Cube_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube001_Cube_2.geometry}
          material={materials["Material.004"]}
        />
      </group>
      <group
        name="Cube_Cube001"
        position={[0.09951669, 0.33894545, -2.33237147]}
        rotation={[Math.PI / 2, 1.5e-7, 1.56757199]}
        scale={[0.15443033, 0.15443033, 0.15443034]}
      >
        <mesh
          name="Cube_Cube001_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_1.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Cube_Cube001_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_2.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          name="Cube_Cube001_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_3.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <mesh
        name="Suelo"
        castShadow
        receiveShadow
        geometry={nodes.Suelo.geometry}
        material={materials.Suelo}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[2.9976995, 2.99770069, 3.45583463]}
      />
      <group
        name="left_table_leg"
        position={[-2.68014097, 0.24947923, -2.41518068]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.00122585}
      >
        <mesh
          name="Pata_Izquierda_Escritorio"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Izquierda_Escritorio.geometry}
          material={materials["paint RAL 7035"]}
        />
        <mesh
          name="Pata_Izquierda_Escritorio_1"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Izquierda_Escritorio_1.geometry}
          material={materials["paint black"]}
        />
        <mesh
          name="Pata_Izquierda_Escritorio_2"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Izquierda_Escritorio_2.geometry}
          material={materials.steel}
        />
        <mesh
          name="Pata_Izquierda_Escritorio_3"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Izquierda_Escritorio_3.geometry}
          material={materials["plastic black"]}
        />
      </group>
      <group
        name="right_table_leg"
        position={[-0.26519734, 0.25098383, -2.4316268]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.00122585}
      >
        <mesh
          name="Pata_Derecha_Escritorio"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Derecha_Escritorio.geometry}
          material={materials["paint RAL 7035"]}
        />
        <mesh
          name="Pata_Derecha_Escritorio_1"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Derecha_Escritorio_1.geometry}
          material={materials["paint black"]}
        />
        <mesh
          name="Pata_Derecha_Escritorio_2"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Derecha_Escritorio_2.geometry}
          material={materials.steel}
        />
        <mesh
          name="Pata_Derecha_Escritorio_3"
          castShadow
          receiveShadow
          geometry={nodes.Pata_Derecha_Escritorio_3.geometry}
          material={materials["plastic black"]}
        />
      </group>
      <mesh
        name="table_top"
        castShadow
        receiveShadow
        geometry={nodes.table_top.geometry}
        material={materials["paint RAL 7035"]}
        position={[-1.54870796, 0.89144427, -2.40909433]}
        rotation={[Math.PI / 2, 1.2e-7, Math.PI / 2]}
        scale={[0.00122585, 0.00198653, 0.00122585]}
      />
      <group
        name="table_top_base"
        position={[-1.47959089, 0.81821996, -2.43162155]}
        rotation={[Math.PI / 2, 8e-8, -Math.PI]}
        scale={[0.00202635, 0.00122585, 0.00122585]}
      >
        <mesh
          name="Base_de_Escritorio"
          castShadow
          receiveShadow
          geometry={nodes.Base_de_Escritorio.geometry}
          material={materials["paint RAL 7035"]}
        />
        <mesh
          name="Base_de_Escritorio_1"
          castShadow
          receiveShadow
          geometry={nodes.Base_de_Escritorio_1.geometry}
          material={materials.steel}
        />
        <mesh
          name="Base_de_Escritorio_2"
          castShadow
          receiveShadow
          geometry={nodes.Base_de_Escritorio_2.geometry}
          material={materials["plastic black"]}
        />
      </group>
      <group
        name="Ventana"
        position={[1.93290544, 1.99467742, -2.94757891]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.20787559, 0.1018196, 0.13761348]}
      >
        <mesh
          name="Ventana_1"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_1.geometry}
          material={materials.Vidrios}
        />
        <mesh
          name="Ventana_2"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_2.geometry}
          material={materials.glass_border1}
        />
        <mesh
          name="Ventana_3"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_3.geometry}
          material={materials.handle}
        />
        <mesh
          name="Ventana_4"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_4.geometry}
          material={materials.window1}
        />
        <mesh
          name="Ventana_5"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_5.geometry}
          material={materials.window2}
        />
        <mesh
          name="Ventana_6"
          castShadow
          receiveShadow
          geometry={nodes.Ventana_6.geometry}
          material={materials.sill}
        />
      </group>
      <group
        name="Clock"
        position={[3.04781961, 0.36529437, 2.49610567]}
        rotation={[Math.PI / 2, 1.5e-7, 2.16094213]}
        scale={[0.00122857, 0.00122858, 0.00122857]}
      >
        <mesh
          name="Mesh_Default_0"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_Default_0.geometry}
          material={materials.clock}
        />
        <mesh
          name="Mesh_Default_0_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_Default_0_1.geometry}
          material={materials["Prism Glass.001"]}
        />
      </group>
      <mesh
        name="Pared_Derecha"
        castShadow
        receiveShadow
        geometry={nodes.Pared_Derecha.geometry}
        material={materials["Pared Derecha"]}
        position={[3.45583391, 2.36847949, 0]}
        rotation={[-Math.PI / 2, -6e-8, -Math.PI / 2]}
        scale={[2.9976995, 2.99770069, 3.16368675]}
      />
      <mesh
        name="Pared_Principal"
        castShadow
        receiveShadow
        geometry={nodes.Pared_Principal.geometry}
        material={materials["Pared Principal"]}
        position={[-0.97169471, 2.33371925, -2.91777635]}
        rotation={[-Math.PI / 2, 4e-8, Math.PI]}
        scale={[3.45583534, 2.99764776, 3.16363096]}
      />
      <mesh
        name="Couch"
        castShadow
        receiveShadow
        geometry={nodes.Couch.geometry}
        material={materials.Chocofur_Fabric_Solid_20}
        position={[0.86724758, 0.40459627, 1.21493912]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.87191516, 1.14971364, 1.15018487]}
      />
    </group>
  );
}

useGLTF.preload("/models/Office.gltf");
